M48
; DRILL file {KiCad 7.0.0-da2b9df05c~163~ubuntu22.04.1} date 2023年03月30日 16時17分36秒
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-30T16:17:36+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0-da2b9df05c~163~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.1181Y-4.626
T0
M30
